### PR TITLE
Automated tests

### PR DESCRIPTION
**Pull request by alekseysemenov**
@ctapobep

### CODE REVIEW

**Comment by ctapobep** [comment]
General impression: I'd try writing component or system tests instead of unit tests. Unit Tests seems useless when you statically mock out everything around..

**Comment by kevstigneev** [comment]
@ctapobep Agree, but it seems not so easy - even Nexus codebase doesn't contain such tests.
I'd suggest to postpone tests re-work to past-1.0. WDYT?

**Comment by ctapobep** [comment]
Yap, makes sense to postpone it.

**Comment by gd-tmagrys** [comment]
My questions/remarks:
- do we need both mockito and PowerMock ? Can we write this tests to use only mockito ?
- I agree with remark to use import static org.unit.Assert.* and then simply only assertEquals()
- @kevstigneev , you'd like me to fix this remarks before release version 1.0 ?

**Comment by alekseysemenov** [comment]
@gd-tmagrys, I agree with @ctapobep we would cut out PowerMock if getConfigurationFile() is package-private. Currently this method has private access and it can not be mocked with Mockito.

**Comment by kevstigneev** [comment]
+1 to excuding this PR from 1.0 scope and re-writing then as @gd-tmagrys suggested.

**Comment by kevstigneev** [comment]
Superseded by PR #30

**Pull request closed without merging**
