### PR TITLE
Update POM to match Maven Central requirements

### PR DESCRIPTION
**Pull request by kevstigneev**
Update the project POM to comply to [Maven Central upload guideline](http://maven.apache.org/guides/mini/guide-central-repository-upload.html).

### CODE REVIEW

**Comment by kevstigneev** [comment]
@alekseysemenov please take care of it..

**Comment by gd-tmagrys** [comment]
I'm fine with this changes. Just wondering if we need this change in documentation file. (We can only use Maven 3.0.4-3.0.5 and cannot use greater versions ?)

**Comment by alekseysemenov** [comment]
Yes we have to use Maven 3.0.4-3.0.5 because of there is maven-enforcer-plugin in the parent artefact of the nexus-replication-plugin. Maven-enforcer-plugin is configured to restrict maven version.

**Comment by gd-tmagrys** [comment]
Ok, I see

**Pull request merged**
